### ISSUE TITLE
Question about unpack()

### ISSUE THREAD

**Issue by sktbrt** [shelfio/aws-lambda-libreoffice#284]
Hi, I want to call soffice.bin directly.
However, it seems that unpack() does not exist above v4 (?)
https://github.com/shelfio/aws-lambda-libreoffice/blob/47e61fc71e0c01ec1f1e358cb9c407c4f4858a35/readme.md?plain=1#L86-L98
Is there a way to do the same?

**Comment by sktbrt** [comment]
Solved

https://github.com/shelfio/aws-lambda-brotli-unpacker

example:
```
const { execSync } = require('child_process');
const { unpack } = require('@shelf/aws-lambda-brotli-unpacker');

module.exports.handler = async event => {
   const inputPath = '/opt/lo.tar.br';
   const outputPath = '/tmp/instdir/program/soffice.bin';
   const command = `${outputPath} ....... --convert-to pdf .......`;
   await unpack({inputPath, outputPath});
   execSync(command);
};
```

NOTE: 
If you use unpack(), the subsequent convertTo() will fail.
So I decided to run everything with execSync.
```
/bin/sh: 1: libreoffice7.4: not found
```

**Comment by cesarpachon** [comment]
hello @sktbrt I recently migrated my lambda from the libreoffice layer to the new docker image, but I am getting an ENOENT: no such file or directory, open '/opt/lo.tar.br' that I reported here:
https://github.com/shelfio/aws-lambda-libreoffice/issues/303

I am totally new to Docker so I am not sure if lo.tar.br is contained in the image or I should somehow install or add it by hand. I am writing this comment here because you mention that specific file in your thread, so hopefully you can provide some hint about how to proceed? it is that "aws-lambda-brotli-unpacker" something that is missing in the docker image and should be installed explicitly? thank you in advance!
